export default {
'loadingDictionaries':'Metadaten werden geladen.',
'loadingDictionariesFailed':'Laden der Metadaten ist fehlgeschlagen.',
'loadingPermissions':'Berechtigungen werden geladen.',
'loadingPermissionsFailed':'Laden der Berechtigungen ist fehlgeschlagen.',
'login':'Anmelden',
'loginFailed':'Einloggen ist fehlgeschlagen.',
'logout':'Abmelden',
'email':'E-Mail',
'username':'Benutzername',
'name':'Name',
'password':'Passwort',
'currentPassword':'Aktuelles Passwort',
'newPassword':'Neues Passwort',
'repeatNewPassword':'Neues Passwort wiederholen',
'forgotPassword':'Passwort vergessen?',
'changePassword':'Passwort Ändern',
'resetPassword':'Passwort zurÃÂ¼cksetzen',
'incorrectPassword':'Passwort ist nicht korrekt.',
}