export default {
'loadingDictionaries':'Metadaten werden.',
'loadingDictionariesFailed':'Laden der Metadaten ist fehlgeschlagen.',
'loadingPermissions':'Berechtigungen werden geladen.',
'loadingPermissionsFailed':'Laden der Berechtigungen ist fehlgeschlagen.',
'login':'Anmelden',
'loginFailed':'Einloggen ist fehlgeschlagen.',
'logout':'Abmelden',
'email':'Swiss email',
'username':'Benutzername',
'name':'Name',
'password':'Passwort',
'currentPassword':'Aktuelles Passwort',
'newPassword':'Neues Passwort',
'repeatNewPassword':'Neues Passwort wiederholen',
'forgotPassword':'Passwort vergessen?',
'changePassword':'Passwort ändern',
'resetPassword':'Passwort zurücksetzen',
'incorrectPassword':'Passwort ist nicht korrekt.',
'repeatedPasswordMismatchError':'Neues Passwort stimmt nicht überein.',
'passwordSpecialCharacterError':'Passwort muss mindestens ein Sonderzeichen enthalten.',
'passwordUpperCaseLetterError':'Passwort muss mindestens einen Grossbuchstaben enthalten',
'passwordLowerCaseLetterError':'Passwort muss mindestens einen Kleinbuchstaben enthalten.',
'passwordDigitError':'Passwort muss mindestens eine Zahl enthalten.',
'currentPasswordIsRequiredError':'Um ein neues Passwort zu setzen, geben Sie bitte das Aktuelle auch ein.',
'newPasswordIsRequiredError':'Neues Password ist ein Pflichtfeld.',
'passwordConfirmationIsRequiredError':'Bitte geben Sie das neue Passwort nochmal ein.',
'applyNewPassword':'Neues Password übernehmen',
'passwordChangeRequestFailed':'Beim Speichern des neuen Passworts auf dem Server ist ein Fehler aufgetreten.',
'passwordChangeSuccess':'Password wurde aktualisiert.',
'register':'Registrieren',
'authentication.description':'Haben Sie bereits ein Login? Dann geben Sie Ihre Anmeldedaten ein oder registrieren Sie sich.',
'authentication.initializationError':'Bei der Initialisierung des Authentifizierungsprozesses ist ein Fehler aufgetreten.',
'insufficientPermissions':'Unzureichende Berechtigungen',
'home':'Swiss Home',
'dateRange':'Laufzeit',
'organizationStructure':'Organisationsstruktur',
'cockpit.myJobs':'Meine Stellen',
'proAnalytics':'ProAnalytics',
'proAnalytics.title':'ProAnalytics',
'proAnalytics.dashboard':'ProAnalytics Dashboard',
'proAnalytics.selectOrganisationNodeRequest':'Bitte setzen Sie zuerst den Filter Organisationsstruktur ein.',
'proAnalytics.jobCountStatistics':'Anzahl Stellen',
'proAnalytics.performanceStatistics':'Performance',
'proAnalytics.performanceStatisticsActionType':'AktionsTyp',
'proAnalytics.viewBy.fieldOfActivity':'Berufsgruppe',
'proAnalytics.careerCenterStatisticsActionType':'AktionsTyp',
'proAnalytics.careerCenterStatistics':'Ihr Stellenmarkt',
'proAnalytics.careerCenterStatisticsUtm':'Stellenaufrufe nach UTM',
'proAnalytics.careerCenterStatisticsSearch':'Suchbegriffe',
'proAnalytics.careerCenterStatisticsSelection':'Filter',
'proAnalytics.careerCenterStatisticsJobabos':'Jobabos',
'proAnalytics.careerCenterStatisticsPrevPeriod':'% Vorperiode',
'proAnalytics.careerCenterStatisticsSearchWeb':'Suchanfragen Internet',
'proAnalytics.careerCenterStatisticsSearchIntranet':'Suchanfragen Intranet',
'proAnalytics.careerCenterStatisticsRank':'Rang',
'proAnalytics.careerCenterStatisticsFilter':'Filter',
'proAnalytics.careerCenterStatisticsElement':'Element',
'proAnalytics.careerCenterStatisticsViews':'Anfragen',
'proAnalytics.careerCenterStatisticsIntranet':'Intranet',
'proAnalytics.careerCenterStatisticsInternet':'Internet',
'proAnalytics.careerCenterStatisticsStelle':'Stelle',
'proAnalytics.careerCenterStatisticsTotal':'Total',
'proAnalytics.careerCenterStatisticsFacebook':'Facebook',
'proAnalytics.careerCenterStatisticsGoogle':'Google',
'proAnalytics.careerCenterStatisticsLinkedIn':'LinkedIn',
'proAnalytics.careerCenterStatisticsDirectLink':'Direktlink',
'proAnalytics.careerCenterStatisticsNoUTM':'kein UTM',
'proAnalytics.careerCenterStatisticsOther':'weitere',
'proAnalytics.performanceStatisticsActionType.clicks':'Klicks',
'proAnalytics.performanceStatisticsActionType.views':'Views',
'proAnalytics.performanceStatisticsActionType.applications':'Bewerbungen',
'proAnalytics.careerCenterStatisticsActionType.utm':'UTM',
'proAnalytics.careerCenterStatisticsActionType.search':'SUCHE',
'proAnalytics.careerCenterStatisticsActionType.selection':'AUSWAHL',
'proAnalytics.viewBy.jobs':'Stellen',
'proAnalytics.candidateJourneyStatistics':'Candidate Journey',
'proAnalytics.costsStatistics':'Kosten',
'proAnalytics.costsProApplication':'Kosten pro Bewerbung',
'proAnalytics.costsProMedium':'Kosten pro Medium',
'proAnalytics.costsPerMediumStatistics':'Kosten pro Medium Statistik',
'proAnalytics.costsProView':'Kosten pro View',
'proAnalytics.costsProClick':'Kosten pro Klick',
'proAnalytics.publicationsPerMedium':'Publikationen pro Medium',
'proAnalytics.viewsPerOnlineDay':'Views/OT',
'proAnalytics.clicksPerOnlineDay':'Bewerberklicks/OT',
'proAnalytics.applicationsPerOnlineDay':'Bewerbungen/OT',
'proAnalytics.applications':'Bewerbungen',
'proAnalytics.clicks':'Bewerberklicks',
'proAnalytics.deviceRatio':'% web|mob',
'proAnalytics.activeJobAds':'Aktive Stellen',
'proAnalytics.pits':'Pits',
'proAnalytics.web':'Web',
'proAnalytics.mobile':'Mobile',
'proAnalytics.search':'Suche',
'proAnalytics.search.placeholder':'Stellentitel, Recruiter, Auftrags-, Publikations- oder Stellennummer',
'proAnalytics.search.recruiterKeyword':'Recruiter',
}