export default {
'loadingDictionaries':'Metadaten werden geladen',
'loadingDictionariesFailed':'Laden der Metadaten ist fehlgeschlagen',
'loadingPermissions':'Berechtigungen werden geladen',
'loadingPermissionsFailed':'Laden der Berechtigungen ist fehlgeschlagen',
'login':'Anmelden',
'loginFailed':'Einloggen ist fehlgeschlagen',
'logout':'Abmelden',
'email':'E-Mail',
'name':'Name',
'username':'Benutzername',
'password':'Passwort',
'currentPassword':'Aktuelles Passwort',
'newPassword':'Neues Passwort',
'repeatNewPassword':'Neues Passwort wiederholen',
'changePassword':'Passwort Ã¤ndern',
'incorrectPassword':'Passwort ist nicht korrekt.',
'repeatedPasswordMismatchError':'Neues Passwort stimmt nicht Ã¼berein.',
'passwordSpecialCharacterError':'Passwort muss mindestens ein Sonderzeichen enthalten.',
'passwordUpperCaseLetterError':'Passwort muss mindestens einen Grossbuchstaben enthalten.',
'passwordLowerCaseLetterError':'Passwort muss mindestens einen Kleinbuchstaben enthalten.',
'passwordDigitError':'Passwort muss mindestens eine Zahl enthalten.',
'currentPasswordIsRequiredError':'Um ein neues Passwort zu setzen, geben Sie bitte das Aktuelle auch ein.',
'newPasswordIsRequiredError':'Neues Passwort ist ein Pflichtfeld.',
'passwordConfirmationIsRequiredError':'Bitte geben Sie das neue Password nochmal ein.',
'applyNewPassword':'',
'passwordChangeRequestFailed':'Beim Speichern des neuen Passworts auf dem Server ist ein Fehler aufgetreten.',
'passwordChangeSuccess':'Passwort wurde aktualisiert.',
'register':'Registrieren',
'forgotPassword':'Passwort vergessen?',
'resetPassword':'Passwort zurÃ¼cksetzen',
'authentication.description':'auth de',
'authentication.initializationError':'auth initi error',
'insufficientPermissions':'',
'home':'',
'dateRange':'New translation',
'organizationStructure':'',
'cockpit.myJobs':'my jobs',
'proAnalytics':'',
'proAnalytics.title':'',
'proAnalytics.dashboard':'',
'proAnalytics.selectOrganisationNodeRequest':'',
'proAnalytics.jobCountStatistics':'',
'proAnalytics.performanceStatistics':'',
'proAnalytics.performanceStatisticsActionType':'',
'proAnalytics.viewBy.fieldOfActivity':'',
'proAnalytics.careerCenterStatisticsActionType':'',
'proAnalytics.careerCenterStatistics':'',
'proAnalytics.careerCenterStatisticsUtm':'',
'proAnalytics.careerCenterStatisticsSearch':'',
'proAnalytics.careerCenterStatisticsSelection':'',
'proAnalytics.careerCenterStatisticsJobabos':'',
'proAnalytics.careerCenterStatisticsPrevPeriod':'',
'proAnalytics.careerCenterStatisticsSearchWeb':'',
'proAnalytics.careerCenterStatisticsSearchIntranet':'',
'proAnalytics.careerCenterStatisticsRank':'',
'proAnalytics.careerCenterStatisticsFilter':'',
'proAnalytics.careerCenterStatisticsElement':'',
'proAnalytics.careerCenterStatisticsViews':'',
'proAnalytics.careerCenterStatisticsIntranet':'',
'proAnalytics.careerCenterStatisticsInternet':'',
'proAnalytics.careerCenterStatisticsStelle':'',
'proAnalytics.careerCenterStatisticsTotal':'',
'proAnalytics.careerCenterStatisticsFacebook':'',
'proAnalytics.careerCenterStatisticsGoogle':'',
'proAnalytics.careerCenterStatisticsLinkedIn':'',
'proAnalytics.careerCenterStatisticsDirectLink':'',
'proAnalytics.careerCenterStatisticsNoUTM':'',
'proAnalytics.careerCenterStatisticsOther':'',
'proAnalytics.performanceStatisticsActionType.clicks':'',
'proAnalytics.performanceStatisticsActionType.views':'',
'proAnalytics.performanceStatisticsActionType.applications':'',
'proAnalytics.careerCenterStatisticsActionType.utm':'',
'proAnalytics.careerCenterStatisticsActionType.search':'',
'proAnalytics.careerCenterStatisticsActionType.selection':'',
'proAnalytics.viewBy.jobs':'',
'proAnalytics.candidateJourneyStatistics':'',
'proAnalytics.costsStatistics':'',
'proAnalytics.costsProApplication':'',
'proAnalytics.costsProMedium':'',
'proAnalytics.costsPerMediumStatistics':'',
'proAnalytics.costsProView':'',
'proAnalytics.costsProClick':'',
'proAnalytics.publicationsPerMedium':'',
'proAnalytics.viewsPerOnlineDay':'',
'proAnalytics.clicksPerOnlineDay':'',
'proAnalytics.applicationsPerOnlineDay':'',
'proAnalytics.applications':'test de',
'proAnalytics.clicks':'',
'proAnalytics.deviceRatio':'',
'proAnalytics.activeJobAds':'',
'proAnalytics.pits':'',
'proAnalytics.web':'',
'proAnalytics.mobile':'',
'proAnalytics.search':'',
'proAnalytics.search.placeholder':'',
'proAnalytics.search.recruiterKeyword':'',
'checkLog':'',
'proAnalytics.view.byJobAd':'',
'proAnalytics.view.byMedium':'',
'proAnalytics.view.byFieldOfActivity':'',
'proAnalytics.candidateJourney.trackingViewsWarning':'',
'proAnalytics.candidateJourney.trackingClicksWarning':'',
'proAnalytics.candidateJourney.trackingApplicationsWarning':'',
'proAnalytics.candidateJourney.trackingViewsInfo':'',
'proAnalytics.candidateJourney.trackingClicksInfo':'',
'proAnalytics.candidateJourney.trackingApplicationsInfo':'',
'proAnalytics.mediaTrackingInfo':'',
'proAnalytics.loadingDictionaries':'',
'proAnalytics.loadingCustomerConfig':'',
'proAnalytics.insufficientPermissions':'',
'proAnalytics.reports.insufficientPermissions':'',
'proAnalytics.rangePickerFormat':'',
'posting.create':'',
'settings.displayOnProfile':'',
'settings.mediaLists':'',
'settings.preferences':'',
'order':'',
'orderId':'',
'posting':'',
'postingId':'',
'publication':'',
'publications':'',
'publicationId':'',
'cockpit':'',
'jobs':'',
'company':'',
'companyName':'',
'country':'',
'country.usa':'',
'country.greatBritain':'',
'country.unitedKingdom':'',
'country.germany':'',
'country.austria':'',
'country.france':'',
'country.italy':'',
'country.switzerland':'',
'language':'',
'language.english':'',
'language.german':'',
'language.french':'',
'language.italian':'',
'language.swissGerman':'',
'settings':'',
'settings.manageMediaList':'',
'settings.yourAccessData':'',
'settings.password.title':'',
'help':'',
'cancel':'',
'timePeriod':'',
'dateFrom':'',
'dateTo':'',
'yesterday':'',
'currentMonth':'',
'lastMonth':'',
'currentYear':'',
'lastYear':'',
'recruiter':'',
'recruiterId':'',
'recruiterName':'',
'recruiters':'',
'allRecruiters':'',
'medium':'',
'mediumId':'',
'media':'',
'media.online':'',
'media.print':'',
'media.ppp':'',
'media.ppd':'',
'media.private':'',
'mediaType':'',
'allMedia':'',
'fieldOfActivity':'',
'allFieldsOfActivity':'',
'industry':'',
'allIndustries':'',
'atsId':'',
'apply':'',
'validator.username.required':'',
'validator.password.required':'',
'validator.email.required':'',
'validator.email.format':'',
'all':'',
'total':'',
'cost':'',
'date':'',
'showMore':'',
'showLess':'',
'search':'',
'state':'',
'overview':'',
'noData':'',
'applications':'',
'clicks':'',
'views':'',
'jobAd':'',
'jobId':'',
'jobAd.internalTitle':'',
'jobAd.externalTitle':'',
'jobAd.title':'',
'kpiStatistics.stellen':'',
'kpiStatistics.publications':'',
'kpiStatistics.costs':'',
'refreshRequest':'',
'recentlyUsed':'',
'information':'',
'webMobile':'',
'back':'',
}