export default {
'loadingDictionaries':'Metadaten werden geladen',
'loadingDictionariesFailed':'Laden der Metadaten ist fehlgeschlagen',
'loadingPermissions':'Berechtigungen werden geladen',
'loadingPermissionsFailed':'Laden der Berechtigungen ist fehlgeschlagen',
'login':'Anmelden',
'loginFailed':'Einloggen ist fehlgeschlagen',
'logout':'Abmelden',
'email':'E-Mail',
'name':'Name',
'username':'Benutzername',
'password':'Passwort',
'currentPassword':'Aktuelles Passwort',
'newPassword':'Neues Passwort',
'repeatNewPassword':'Neues Passwort wiederholen',
'changePassword':'Passwort ändern',
'incorrectPassword':'Passwort ist nicht korrekt.',
'repeatedPasswordMismatchError':'Neues Passwort stimmt nicht überein.',
'passwordSpecialCharacterError':'Passwort muss mindestens ein Sonderzeichen enthalten.',
'passwordUpperCaseLetterError':'Passwort muss mindestens einen Grossbuchstaben enthalten.',
'passwordLowerCaseLetterError':'Passwort muss mindestens einen Kleinbuchstaben enthalten.',
'passwordDigitError':'Passwort muss mindestens eine Zahl enthalten.',
'currentPasswordIsRequiredError':'Um ein neues Passwort zu setzen, geben Sie bitte das Aktuelle auch ein.',
'newPasswordIsRequiredError':'Neues Passwort ist ein Pflichtfeld.',
'passwordConfirmationIsRequiredError':'Bitte geben Sie das neue Password nochmal ein.',
'applyNewPassword':'Neues Passwort übernehmen',
'passwordChangeRequestFailed':'Beim Speichern des neuen Passworts auf dem Server ist ein Fehler aufgetreten.',
'passwordChangeSuccess':'Passwort wurde aktualisiert.',
'register':'Registrieren',
'forgotPassword':'Passwort vergessen?',
'resetPassword':'Passwort zurücksetzen',
'authentication.description':'auth de',
'authentication.initializationError':'auth initi error',
'insufficientPermissions':'',
'home':'',
'dateRange':'',
'organizationStructure':'',
'cockpit.myJobs':'',
'proAnalytics':'',
'proAnalytics.title':'',
'proAnalytics.dashboard':'',
'proAnalytics.selectOrganisationNodeRequest':'',
'proAnalytics.jobCountStatistics':'',
'proAnalytics.performanceStatistics':'',
'proAnalytics.performanceStatisticsActionType':'',
'proAnalytics.viewBy.fieldOfActivity':'',
'proAnalytics.careerCenterStatisticsActionType':'',
'proAnalytics.careerCenterStatistics':'',
'proAnalytics.careerCenterStatisticsUtm':'',
'proAnalytics.careerCenterStatisticsSearch':'',
'proAnalytics.careerCenterStatisticsSelection':'',
'proAnalytics.careerCenterStatisticsJobabos':'',
'proAnalytics.careerCenterStatisticsPrevPeriod':'',
'proAnalytics.careerCenterStatisticsSearchWeb':'',
'proAnalytics.careerCenterStatisticsSearchIntranet':'',
'proAnalytics.careerCenterStatisticsRank':'',
'proAnalytics.careerCenterStatisticsFilter':'',
'proAnalytics.careerCenterStatisticsElement':'',
'proAnalytics.careerCenterStatisticsViews':'',
'proAnalytics.careerCenterStatisticsIntranet':'',
'proAnalytics.careerCenterStatisticsInternet':'',
'proAnalytics.careerCenterStatisticsStelle':'',
'proAnalytics.careerCenterStatisticsTotal':'',
'proAnalytics.careerCenterStatisticsFacebook':'',
'proAnalytics.careerCenterStatisticsGoogle':'',
'proAnalytics.careerCenterStatisticsLinkedIn':'',
'proAnalytics.careerCenterStatisticsDirectLink':'',
'proAnalytics.careerCenterStatisticsNoUTM':'',
'proAnalytics.careerCenterStatisticsOther':'',
'proAnalytics.performanceStatisticsActionType.clicks':'',
'proAnalytics.performanceStatisticsActionType.views':'',
'proAnalytics.performanceStatisticsActionType.applications':'',
'proAnalytics.careerCenterStatisticsActionType.utm':'',
'proAnalytics.careerCenterStatisticsActionType.search':'',
'proAnalytics.careerCenterStatisticsActionType.selection':'',
'proAnalytics.viewBy.jobs':'',
'proAnalytics.candidateJourneyStatistics':'',
'proAnalytics.costsStatistics':'',
'proAnalytics.costsProApplication':'',
'proAnalytics.costsProMedium':'',
'proAnalytics.costsPerMediumStatistics':'',
'proAnalytics.costsProView':'',
'proAnalytics.costsProClick':'',
'proAnalytics.publicationsPerMedium':'',
'proAnalytics.viewsPerOnlineDay':'',
'proAnalytics.clicksPerOnlineDay':'',
'proAnalytics.applicationsPerOnlineDay':'',
'proAnalytics.applications':'',
'proAnalytics.clicks':'',
'proAnalytics.deviceRatio':'',
'proAnalytics.activeJobAds':'',
'proAnalytics.pits':'',
'proAnalytics.web':'',
'proAnalytics.mobile':'',
'proAnalytics.search':'',
'proAnalytics.search.placeholder':'',
'proAnalytics.search.recruiterKeyword':'',
}