export default {
'passwordValidationRules':'minLength => `Password has to be at least ${minLength} characters long and must contain uppercase letters, lowercase letters, numbers and a special character.`',
'loadingDictionaries':'Metadata is loading',
'loadingDictionariesFailed':'Loading of metadata failed',
'loadingPermissions':'Permissions are loading',
'loadingPermissionsFailed':'Loading of permissions failed',
'login':'Log in',
'loginFailed':'Login failed',
'logout':'Log out',
'email':'Email',
'name':'Name',
'username':'User name',
'password':'Password',
'currentPassword':'Current password',
'newPassword':'New password',
'repeatNewPassword':'Repeat new password',
'changePassword':'Change password',
'incorrectPassword':'Password is incorrect',
'forgotPassword':'',
'resetPassword':'',
'repeatedPasswordMismatchError':'',
'passwordSpecialCharacterError':'',
'passwordUpperCaseLetterError':'',
'passwordLowerCaseLetterError':'',
'passwordDigitError':'',
'currentPasswordIsRequiredError':'Testsss',
'newPasswordIsRequiredError':'',
'passwordConfirmationIsRequiredError':'',
'applyNewPassword':'test onessssss',
'passwordChangeRequestFailed':'',
'passwordChangeSuccess':'',
'register':'',
'authentication.description':'auth descriptions',
'authentication.initializationError':'authentication initialization errosssr',
'insufficientPermissions':'',
'home':'',
'dateRange':'date ranges',
'organizationStructure':'',
'cockpit.myJobs':'Cockpit stuff',
'proAnalytics':'',
'proAnalytics.title':'',
'proAnalytics.dashboard':'dashboard',
'proAnalytics.selectOrganisationNodeRequest':'',
'proAnalytics.jobCountStatistics':'',
'proAnalytics.performanceStatistics':'',
'proAnalytics.performanceStatisticsActionType':'',
'proAnalytics.viewBy.fieldOfActivity':'',
'proAnalytics.careerCenterStatisticsActionType':'',
'proAnalytics.careerCenterStatistics':'',
'proAnalytics.careerCenterStatisticsUtm':'',
'proAnalytics.careerCenterStatisticsSearch':'',
'proAnalytics.careerCenterStatisticsSelection':'',
'proAnalytics.careerCenterStatisticsJobabos':'',
'proAnalytics.careerCenterStatisticsPrevPeriod':'',
'proAnalytics.careerCenterStatisticsSearchWeb':'',
'proAnalytics.careerCenterStatisticsSearchIntranet':'',
'proAnalytics.careerCenterStatisticsRank':'',
'proAnalytics.careerCenterStatisticsFilter':'',
'proAnalytics.careerCenterStatisticsElement':'',
'proAnalytics.careerCenterStatisticsViews':'',
'proAnalytics.careerCenterStatisticsIntranet':'',
'proAnalytics.careerCenterStatisticsInternet':'',
'proAnalytics.careerCenterStatisticsStelle':'',
'proAnalytics.careerCenterStatisticsTotal':'',
'proAnalytics.careerCenterStatisticsFacebook':'',
'proAnalytics.careerCenterStatisticsGoogle':'',
'proAnalytics.careerCenterStatisticsLinkedIn':'',
'proAnalytics.careerCenterStatisticsDirectLink':'',
'proAnalytics.careerCenterStatisticsNoUTM':'',
'proAnalytics.careerCenterStatisticsOther':'',
'proAnalytics.performanceStatisticsActionType.clicks':'',
'proAnalytics.performanceStatisticsActionType.views':'',
'proAnalytics.performanceStatisticsActionType.applications':'',
'proAnalytics.careerCenterStatisticsActionType.utm':'',
'proAnalytics.careerCenterStatisticsActionType.search':'',
'proAnalytics.careerCenterStatisticsActionType.selection':'',
'proAnalytics.viewBy.jobs':'',
'proAnalytics.candidateJourneyStatistics':'',
'proAnalytics.costsStatistics':'costs',
'proAnalytics.costsProApplication':'',
'proAnalytics.costsProMedium':'',
'proAnalytics.costsPerMediumStatistics':'',
'proAnalytics.costsProView':'',
'proAnalytics.costsProClick':'',
'proAnalytics.publicationsPerMedium':'',
'proAnalytics.viewsPerOnlineDay':'',
'proAnalytics.clicksPerOnlineDay':'',
'proAnalytics.applicationsPerOnlineDay':'',
'proAnalytics.applications':'test',
'proAnalytics.clicks':'',
'proAnalytics.deviceRatio':'',
'proAnalytics.activeJobAds':'',
'proAnalytics.pits':'',
'proAnalytics.web':'',
'proAnalytics.mobile':'',
'proAnalytics.search':'',
'proAnalytics.search.placeholder':'',
'proAnalytics.search.recruiterKeyword':'',
}