export default {
    loadingDictionaries: "Métadonnées en cours de chargement",
    loadingDictionariesFailed: "Échec du chargement des métadonnées",
    loadingPermissions: "Autorisations en cours de chargement",
    loadingPermissionsFailed: "Échec du chargement des autorisations",
    login: "Connexion",
    loginFailed: "Échec de la connexion",
    logout: "Déconnexion",
    email: "E-mail",
    username: "Identifiant",
    password: "Mot de passe",
    register: "Inscription",
    forgotPassword: "Mot de passe oublié?",
    resetPassword: "Réinitialisation du mot de passe",
    "authentication.description":
        "Avez-vous déjà un compte d’utilisateur? Alors saisissez vos données de connexion ou inscrivez-vous.",
    "authentication.initializationError": `Une erreur est survenue lors de l'initialisation du processus d'authentification`,
    home: "Accueil",
    dateRange: "Plage de dates",
    organizationStructure: "Structure organisationnelle",
    proAnalytics: "ProAnalytics",
    "proAnalytics.title": "ProAnalytics",
    "proAnalytics.dashboard": "ProAnalytics Dashboard",
    "proAnalytics.selectOrganisationNodeRequest": `Veuillez d'abord mettre le filtre Structure organisationnelle`,
    "proAnalytics.jobCountStatistics": "Nombre de postes",
};
