export default {
'loadingDictionaries':'Métadonnées en cours de chargement',
'loadingDictionariesFailed':'Échec du chargement des métadonnées',
'loadingPermissions':'Autorisations en cours de chargement',
'loadingPermissionsFailed':'Échec du chargement des autorisations',
'login':'Connexion',
'loginFailed':'Échec de la connexion',
'logout':'Déconnexion',
'email':'E-mail',
'username':'Identifiant',
'password':'Mot de passe',
'register':'Inscription',
'forgotPassword':'Mot de passe oublié?',
'resetPassword':'Réinitialisation du mot de passe',
'authentication.description':'Avez-vous déjà un compte d’utilisateur? Alors saisissez vos données de connexion ou inscrivez-vous.',
'home':'Accueil',
'dateRange':'Plage de dates',
'organizationStructure':'Structure organisationnelle',
'proAnalytics':'ProAnalytics',
'proAnalytics.title':'ProAnalytics',
'proAnalytics.dashboard':'ProAnalytics Dashboard',
'proAnalytics.selectOrganisationNodeRequest':'Veuillez d'abord mettre le filtre Structure organisationnelle',
'proAnalytics.jobCountStatistics':'Nombre de postes',
'name':'',
'currentPassword':'french translation',
'newPassword':'',
'repeatNewPassword':'',
'changePassword':'',
'incorrectPassword':'',
'repeatedPasswordMismatchError':'',
'passwordSpecialCharacterError':'',
'passwordUpperCaseLetterError':'',
'passwordLowerCaseLetterError':'',
'passwordDigitError':'',
'currentPasswordIsRequiredError':'',
'newPasswordIsRequiredError':'',
'passwordConfirmationIsRequiredError':'',
'applyNewPassword':'',
'passwordChangeRequestFailed':'',
'passwordChangeSuccess':'',
'insufficientPermissions':'',
'cockpit.myJobs':'',
'proAnalytics.performanceStatistics':'',
'proAnalytics.performanceStatisticsActionType':'',
'proAnalytics.viewBy.fieldOfActivity':'',
'proAnalytics.careerCenterStatisticsActionType':'',
'proAnalytics.careerCenterStatistics':'',
'proAnalytics.careerCenterStatisticsUtm':'',
'proAnalytics.careerCenterStatisticsSearch':'',
'proAnalytics.careerCenterStatisticsSelection':'',
'proAnalytics.careerCenterStatisticsJobabos':'',
'proAnalytics.careerCenterStatisticsPrevPeriod':'',
'proAnalytics.careerCenterStatisticsSearchWeb':'',
'proAnalytics.careerCenterStatisticsSearchIntranet':'',
'proAnalytics.careerCenterStatisticsRank':'',
'proAnalytics.careerCenterStatisticsFilter':'',
'proAnalytics.careerCenterStatisticsElement':'',
'proAnalytics.careerCenterStatisticsViews':'',
'proAnalytics.careerCenterStatisticsIntranet':'',
'proAnalytics.careerCenterStatisticsInternet':'',
'proAnalytics.careerCenterStatisticsStelle':'',
'proAnalytics.careerCenterStatisticsTotal':'',
'proAnalytics.careerCenterStatisticsFacebook':'',
'proAnalytics.careerCenterStatisticsGoogle':'',
'proAnalytics.careerCenterStatisticsLinkedIn':'',
'proAnalytics.careerCenterStatisticsDirectLink':'',
'proAnalytics.careerCenterStatisticsNoUTM':'',
'proAnalytics.careerCenterStatisticsOther':'',
'proAnalytics.performanceStatisticsActionType.clicks':'',
'proAnalytics.performanceStatisticsActionType.views':'',
'proAnalytics.performanceStatisticsActionType.applications':'',
'proAnalytics.careerCenterStatisticsActionType.utm':'',
'proAnalytics.careerCenterStatisticsActionType.search':'',
'proAnalytics.careerCenterStatisticsActionType.selection':'',
'proAnalytics.viewBy.jobs':'',
'proAnalytics.candidateJourneyStatistics':'',
'proAnalytics.costsStatistics':'',
'proAnalytics.costsProApplication':'',
'proAnalytics.costsProMedium':'',
'proAnalytics.costsPerMediumStatistics':'',
'proAnalytics.costsProView':'',
'proAnalytics.costsProClick':'',
'proAnalytics.publicationsPerMedium':'',
'proAnalytics.viewsPerOnlineDay':'',
'proAnalytics.clicksPerOnlineDay':'',
'proAnalytics.applicationsPerOnlineDay':'',
'proAnalytics.applications':'',
'proAnalytics.clicks':'',
'proAnalytics.deviceRatio':'',
'proAnalytics.activeJobAds':'',
'proAnalytics.pits':'',
'proAnalytics.web':'',
'proAnalytics.mobile':'',
'proAnalytics.search':'',
'proAnalytics.search.placeholder':'',
'proAnalytics.search.recruiterKeyword':'',
}
