export default {
	'dateFormatter': date => date ? `${date.getDate().toString().padStart(2, '0')}/${(date.getMonth() + 1).toString().padStart(2, '0')}/${date.getFullYear()}` : ' - ',
    'dateFormatter.shortDate': date => date ? `${date.getDate().toString().padStart(2, '0')}/${(date.getMonth() + 1).toString().padStart(2, '0')}/${date.getFullYear()}` : ' - ',
    'monthFormatter': date => date ? date.toLocaleString('it-IT', {year: 'numeric', month: 'long'}) : ' - ', // November 2021
    'weekFormatter': date => date ? `W${getWeek(date)} ${date.getFullYear()}` : ' - ', // W28 2021
    'priceFormatter': (price, currency) => currency ? price.toLocaleString('it-IT', {style: 'currency', currency}) : price.toLocaleString('it-IT', {minimumFractionDigits: 2, maximumFractionDigits: 2}),
    'numberFormatter': (number) => number ? number.toLocaleString('it-IT', {minimumFractionDigits: 0, maximumFractionDigits: 0}):0,
    'twoDigitFormatter': (number) => number ? number.toLocaleString('it-IT', {minimumFractionDigits: 2, maximumFractionDigits: 2}):0,
	'loadingDictionaries': 'Caricamento dei metadati in corso',
	'loadingDictionariesFailed': 'Caricamento dei metadati fallito',
	'loadingPermissions': 'Caricamento delle autorizzazioni in corso',
	'loadingPermissionsFailed': 'Caricamento delle autorizzazioni fallito',
	'login': 'Accedere',
	'loginFailed': 'Accesso fallito',
	'logout': 'Uscire',
	'email': 'E-mail',
	'username': 'Nome utente',
	'password': 'Password',
	'register': 'Registrarsi',
	'forgotPassword': 'Password dimenticata?',
	'resetPassword': 'Reimpostare la password',
	'authentication.description': 'Ha già un login? Inserisca i suoi dati d’accesso o si registri',
	'authentication.initializationError': `Si è verificato un errore durante l’inizializzazione del processo di autenticazione`,
	'home': 'Home',
	'dateRange': 'Intervallo di date',
	'organizationStructure': 'Struttura organizzativa',
	'proAnalytics': 'ProAnalytics',
	'proAnalytics.title': 'ProAnalytics',
	'proAnalytics.dashboard': 'Dashboard ProAnalytics',
	'proAnalytics.selectOrganisationNodeRequest': 'Si prega di impostare prima il filtro Struttura organizzativa',
	'proAnalytics.jobCountStatistics': 'Numero di posti',
	'proAnalytics.jobCountStatistics.average': (value) =>
		`${Number(value).toLocaleString('it-CH', { maximumFractionDigits: 2 })} Posti vacanti in media/giorno`,
	'proAnalytics.performanceStatistics': 'Performance',
	'proAnalytics.performanceStatisticsActionType': 'Tipo di azione',
	'proAnalytics.viewBy.fieldOfActivity': 'Categoria professionale',
	'proAnalytics.careerCenterStatisticsActionType': 'Tipo di azione',
	'proAnalytics.careerCenterStatistics': 'Le sue offerte di lavoro',
	'proAnalytics.careerCenterStatisticsUtm': 'Richiami alle offerte di lavoro secondo UTM',
	'proAnalytics.careerCenterStatisticsSearch': 'Termini di ricerca',
	'proAnalytics.careerCenterStatisticsSelection': 'Selezione',
	'proAnalytics.careerCenterStatisticsJobabos': 'Abbonamenti alle offerte di lavoro',
	'proAnalytics.careerCenterStatisticsPrevPeriod': '% periodo precedente',
	'proAnalytics.careerCenterStatisticsSearchWeb': 'Ricerche web',
	'proAnalytics.careerCenterStatisticsSearchIntranet': 'Ricerche intranet',
	'proAnalytics.careerCenterStatisticsRank': 'Rang',
	'proAnalytics.careerCenterStatisticsFilter': 'Filtro',
	'proAnalytics.careerCenterStatisticsElement': 'Elemento',
	'proAnalytics.careerCenterStatisticsViews': 'Richiami',
	'proAnalytics.careerCenterStatisticsIntranet': 'Intranet',
	'proAnalytics.careerCenterStatisticsInternet': 'Internet',
	'proAnalytics.careerCenterStatisticsStelle': 'Posto',
	'proAnalytics.careerCenterStatisticsTotal': 'Totale',
	'proAnalytics.careerCenterStatisticsFacebook': 'Facebook',
	'proAnalytics.careerCenterStatisticsGoogle': 'Google',
	'proAnalytics.careerCenterStatisticsLinkedIn': 'LinkedIn',
	'proAnalytics.careerCenterStatisticsDirectLink': 'Link diretto',
	'proAnalytics.careerCenterStatisticsNoUTM': 'senza UTM',
	'proAnalytics.careerCenterStatisticsOther': 'altri',
	'proAnalytics.performanceStatisticsActionType.clicks': 'Clicks',
	'proAnalytics.performanceStatisticsActionType.views': 'Views',
	'proAnalytics.performanceStatisticsActionType.applications': 'Applications',
	'proAnalytics.careerCenterStatisticsActionType.utm': 'UTM',
	'proAnalytics.careerCenterStatisticsActionType.search': 'RICERCA',
	'proAnalytics.careerCenterStatisticsActionType.selection': 'SELEZIONE',
	'proAnalytics.viewBy.jobs': 'Posti',
	'proAnalytics.candidateJourneyStatistics': 'Candidate Journey',
	'proAnalytics.costsStatistics': 'Costi',
	'proAnalytics.costsProApplication': 'Costo per domanda',
	'proAnalytics.costsProMedium': 'Costi per canale',
	'proAnalytics.costsPerMediumStatistics': 'Costi per canale statistiche',
	'proAnalytics.costsProView': 'Costi per richiamo',
	'proAnalytics.costsProClick': 'Costi per clic',
	'proAnalytics.publicationsPerMedium': 'Pubblicazioni per canale',
	'proAnalytics.viewsPerOnlineDay': 'Richiami/GO',
	'proAnalytics.clicksPerOnlineDay': 'Clic di candidati/GO',
	'proAnalytics.clicks': 'Clic',
	'proAnalytics.applicationsPerOnlineDay': 'Candidature/GO',
	'proAnalytics.applications': 'Applicazioni',
	'proAnalytics.deviceRatio': '% web|mob',
	'proAnalytics.search': 'Ricerca',
	'proAnalytics.search.placeholder':
		'Titolo del posto, recruiter, numero di mandato, di pubblicazione o di posto',
	'proAnalytics.search.recruiterKeyword': 'Recruiter',
	'proAnalytics.search.termEverywhere': ({ searchTerm, hitCount }) =>
		`Risultati per '${searchTerm}' ${hitCount === undefined ? '' : `(${hitCount})`}`,
	'proAnalytics.search.termInColumn': ({ searchTerm, fieldName, hitCount }) =>
		`Risultati per '${searchTerm}' in ${fieldName} (${hitCount})`,
	'proAnalytics.search.resultInfo': ({ searchTerm, fieldName, hitCount }) =>
		`${hitCount} ${hitCount === 1 ? 'Risultato' : 'Risultati'} per ${searchTerm} in ${fieldName}`,
	'proAnalytics.search.jobTitle': (jobTitle) => `Titolo professionale: '${jobTitle}'`,
	'proAnalytics.search.externalJobTitle': (jobTitle) => `Titolo professionale esterno: '${jobTitle}'`,
	'proAnalytics.search.postingId': (id) => `Numero del posto: '${id}'`,
	'proAnalytics.search.publicationId': (id) => `Numero di pubblicazione: '${id}'`,
	'proAnalytics.search.orderId': (id) => `Numero di mandato: '${id}'`,
	'proAnalytics.dateRange.autoCorrectionWarning': ({ start, end }) =>
		`Sono disponibili i dati degli ultimi due anni. Il suo filtro è stato regolato di conseguenza.`,
	'proAnalytics.dictionaries.error': ({ logNumber }) =>
		'Impossibile aggiornare il filtro Dictionaries. I dettagli tecnici sono nel log #${logNumber}.',
	'proAnalytics.search.error': ({ logNumber }) =>
		`La ricerca è fallita. I dettagli tecnici sono nel log #${logNumber}.`,
	'proAnalytics.jobCount.error': ({ logNumber }) =>
		`Non è stato possibile caricare il numero di posti. I dettagli tecnici sono nel log #${logNumber}.`,
	'proAnalytics.performance.error': ({ logNumber }) =>
		`Non è stato possibile caricare i dati di performance. I dettagli tecnici sono nel log #${logNumber}.`,
	'proAnalytics.candidateJourney.error': ({ logNumber }) =>
		`Non è stato possibile caricare i dati della Candidate Journey. I dettagli tecnici sono nel log #${logNumber}.`,
	'proAnalytics.costs.error': ({ logNumber }) =>
		`Non è stato possibile caricare i dati sui costi. I dettagli tecnici sono nel log #${logNumber}.`,
	'proAnalytics.careerCenter.error': ({ logNumber }) =>
		`Non è stato possibile caricare le statistiche sulle offerte di lavoro. I dettagli tecnici sono nel log #${logNumber}.`,
	'proAnalytics.moreFilters': 'Più filtri',
	'proAnalytics.lessFilters': 'Meno filtri',
	'proAnalytics.resetFilters': 'Ripristinare tutto',
	'proAnalytics.maxDatasetsNumberInfo': (maxDatasetsNumber) =>
		`Può visualizzare un massimo di ${maxDatasetsNumber} dataset.`,
	'proAnalytics.view.byJobAd': 'per posto',
	'proAnalytics.view.byMedium': 'per canale',
	'proAnalytics.view.byFieldOfActivity': 'per categoria professionale',
	'proAnalytics.candidateJourney.trackingViewsWarning': 'Per alcuni canali, non è possibile misurare i richiami.',
	'proAnalytics.candidateJourney.trackingClicksWarning': 'Per alcuni canali, non è possibile misurare i clic.',
	'proAnalytics.candidateJourney.trackingApplicationsWarning':
		'Per alcuni canali, non è possibile misurare le candidature.',
	'proAnalytics.candidateJourney.trackingViewsInfo': 'La statistica mostrata presenta le cifre corrette.',
	'proAnalytics.candidateJourney.trackingClicksInfo': 'La statistica mostrata presenta le cifre corrette.',
	'proAnalytics.candidateJourney.trackingApplicationsInfo': 'La statistica mostrata presenta le cifre corrette.',
	'proAnalytics.mediaTrackingInfo': 'Informazioni sul tracking del canale',
	'proAnalytics.loadingDictionaries': 'Caricamento dei dictionary in corso',
	'proAnalytics.rangePickerFormat': 'DD/MM/YYYY',
	'posting.create': 'Creare un nuovo annuncio',
	'order': 'Mandato',
	'orderId': 'ID mandato',
	'posting': 'Annuncio',
	'postingId': 'ID annuncio',
	'publication': 'Pubblicazione',
	'publications': 'Pubblicazioni',
	'publicationId': 'ID pubblicazione',
	'cockpit': 'Cockpit',
	'jobs': 'Posti',
	'company': 'Azienda',
	'companyName': 'Nome azienda',
	'country': 'Paese',
	'country.usa': 'USA',
	'country.greatBritain': 'Gran Bretagna',
	'country.unitedKingdom': 'Gran Bretagna',
	'country.germany': 'Germania',
	'country.austria': 'Austria',
	'country.france': 'Francia',
	'country.italy': 'Italia',
	'country.switzerland': 'Svizzera',
	'language': 'Lingua',
	'language.english': 'Inglese',
	'language.german': 'Tedesco',
	'language.french': 'Francese',
	'language.italian': 'Italiano',
	'language.swissGerman': 'Svizzero tedesco',
	'settings': 'Impostazioni',
	'help': 'Aiuto',
	'cancel': 'Annullare',
	'timePeriod': 'Periodo',
	'dateFrom': 'Da',
	'dateTo': 'A',
	'yesterday': 'Ieri',
	'currentMonth': 'Mese corrente',
	'lastMonth': 'Il mese scorso',
	'currentYear': 'Anno corrente',
	'lastYear': 'L’anno scorso',
	'recruiter': 'Recruiter',
	'recruiterId': 'ID recruiter',
	'recruiterName': 'Nome recruiter',
	'recruiters': 'Recruiter',
	'allRecruiters': 'Tutti i recruiter',
	'medium': 'Canale',
	'mediumId': 'ID canale',
	'media': 'Canali',
	'media.online': 'Online',
	'media.print': 'Stampa',
	'media.ppp': 'PPP',
	'media.ppd': 'PPD',
	'media.private': 'Privato',
	'mediaType': 'Tipo di media',
	'allMedia': 'Tutti i canali',
	'fieldOfActivity': 'Categoria professionale',
	'allFieldsOfActivity': 'Tutte le categorie professionali',
	'industry': 'Settore',
	'allIndustries': 'Tutti i settori',
	'atsId': 'ID interno o ID ATS',
	'apply': 'Applicare',
	'validator.username.required': 'Inserisca il suo nome utente.',
	'validator.password.required': 'Inserisca la sua password.',
	'validator.email.required': 'Inserisca l’indirizzo e-mail.',
	'validator.email.format': 'L’indirizzo e-mail inserito non è corretto',
	'all': 'Tutti',
	'total': 'Totale',
	'cost': 'Costi',
	'date': 'Data',
	'other': (count) => (count !== undefined ? `Altri (${count})` : 'Altri'),
	'showMore': 'Più',
	'showLess': 'Meno',
	'state': 'Stato',
	'overview': 'Panoramica',
	'noData': 'Nessun dato',
	'applications': 'Candidature',
	'clicks': 'Clic',
	'views': 'Richiami',
	'jobAd': 'Posto',
	'jobId': 'Posto ID',
	'jobAd.internalTitle': 'Titolo (interno)',
	'jobAd.externalTitle': 'Titolo (esterno)',
	'jobAd.title': 'Titolo',
	'kpiStatistics.stellen': 'Posti',
	'kpiStatistics.publications': 'Pubblicazioni',
	'kpiStatistics.costs': 'Costi',
	'checkLog': (logNumber) => `I dettagli tecnici sono nel log #${logNumber}.`,
	'unexpectedError': ({ logNumber }) => `Qualcosa è andato storto. I dettagli tecnici sono nel log #${logNumber}.`,
	'refreshRequest': 'Si prega di ricaricare l’applicazione o di riprovare più tardi.',
	'recentlyUsed': 'Ultimo utilizzo',
	'information': 'Informazione',
	'webMobile': 'Distribuzione Web-Mobile',
	'back': 'Indietro'
}
