export default {
    loadingDictionaries: "Caricamento dei metadati in corso",
    loadingDictionariesFailed: "Caricamento dei metadati fallito",
    loadingPermissions: "Caricamento delle autorizzazioni in corso",
    loadingPermissionsFailed: "Caricamento delle autorizzazioni fallito",
    login: "Accedere",
    loginFailed: "Accesso fallito",
    logout: "Uscire",
    email: "E-mail",
    username: "Nome utente",
    password: "Password",
    register: "Registrarsi",
    forgotPassword: "Password dimenticata?",
    resetPassword: "Reimpostare la password",
    "authentication.description": "Ha già un login? Inserisca i suoi dati d’accesso o si registri",
    "authentication.initializationError": `Si è verificato un errore durante l’inizializzazione del processo di autenticazione`,
    home: "Home",
    dateRange: "Intervallo di date",
    organizationStructure: "Struttura organizzativa",
    proAnalytics: "ProAnalytics",
    "proAnalytics.title": "ProAnalytics",
    "proAnalytics.dashboard": "Dashboard ProAnalytics",
    "proAnalytics.selectOrganisationNodeRequest": "Si prega di impostare prima il filtro Struttura organizzativa",
    "proAnalytics.jobCountStatistics": "Numero di posti",
    "proAnalytics.performanceStatistics": "Performance",
    "proAnalytics.performanceStatisticsActionType": "Tipo di azione",
    "proAnalytics.viewBy.fieldOfActivity": "Categoria professionale",
    "proAnalytics.careerCenterStatisticsActionType": "Tipo di azione",
    "proAnalytics.careerCenterStatistics": "Le sue offerte di lavoro",
    "proAnalytics.careerCenterStatisticsUtm": "Richiami alle offerte di lavoro secondo UTM",
    "proAnalytics.careerCenterStatisticsSearch": "Termini di ricerca",
    "proAnalytics.careerCenterStatisticsSelection": "Selezione",
    "proAnalytics.careerCenterStatisticsJobabos": "Abbonamenti alle offerte di lavoro",
    "proAnalytics.careerCenterStatisticsPrevPeriod": "% periodo precedente",
    "proAnalytics.careerCenterStatisticsSearchWeb": "Ricerche web",
    "proAnalytics.careerCenterStatisticsSearchIntranet": "Ricerche intranet",
    "proAnalytics.careerCenterStatisticsRank": "Rang",
    "proAnalytics.careerCenterStatisticsFilter": "Filtro",
    "proAnalytics.careerCenterStatisticsElement": "Elemento",
    "proAnalytics.careerCenterStatisticsViews": "Richiami",
    "proAnalytics.careerCenterStatisticsIntranet": "Intranet",
    "proAnalytics.careerCenterStatisticsInternet": "Internet",
    "proAnalytics.careerCenterStatisticsStelle": "Posto",
    "proAnalytics.careerCenterStatisticsTotal": "Totale",
    "proAnalytics.careerCenterStatisticsFacebook": "Facebook",
    "proAnalytics.careerCenterStatisticsGoogle": "Google",
    "proAnalytics.careerCenterStatisticsLinkedIn": "LinkedIn",
    "proAnalytics.careerCenterStatisticsDirectLink": "Link diretto",
    "proAnalytics.careerCenterStatisticsNoUTM": "senza UTM",
    "proAnalytics.careerCenterStatisticsOther": "altri",
    "proAnalytics.performanceStatisticsActionType.clicks": "Clicks",
    "proAnalytics.performanceStatisticsActionType.views": "Views",
    "proAnalytics.performanceStatisticsActionType.applications": "Applications",
    "proAnalytics.careerCenterStatisticsActionType.utm": "UTM",
    "proAnalytics.careerCenterStatisticsActionType.search": "RICERCA",
    "proAnalytics.careerCenterStatisticsActionType.selection": "SELEZIONE",
    "proAnalytics.viewBy.jobs": "Posti",
    "proAnalytics.candidateJourneyStatistics": "Candidate Journey",
    "proAnalytics.costsStatistics": "Costi",
    "proAnalytics.costsProApplication": "Costo per domanda",
    "proAnalytics.costsProMedium": "Costi per canale",
    "proAnalytics.costsPerMediumStatistics": "Costi per canale statistiche",
    "proAnalytics.costsProView": "Costi per richiamo",
    "proAnalytics.costsProClick": "Costi per clic",
    "proAnalytics.publicationsPerMedium": "Pubblicazioni per canale",
    "proAnalytics.viewsPerOnlineDay": "Richiami/GO",
    "proAnalytics.clicksPerOnlineDay": "Clic di candidati/GO",
    "proAnalytics.clicks": "Clic",
    "proAnalytics.applicationsPerOnlineDay": "Candidature/GO",
    "proAnalytics.applications": "Applicazioni",
    "proAnalytics.deviceRatio": "% web|mob",
    "proAnalytics.search": "Ricerca",
    "proAnalytics.search.placeholder": "Titolo del posto, recruiter, numero di mandato, di pubblicazione o di posto",
    "proAnalytics.search.recruiterKeyword": "Recruiter",
};
